### ISSUE TITLE
Error when closing a grid

### ISSUE THREAD

**Issue by SWQXDBA** [N1Ran/BlockLimiter#102]
## log:
```
23:02:12.9521 [ERROR]  Torch.Managers.PluginManager: Plugin TestPlugin threw an exception during update!
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at BlockLimiter.Patch.GridChange.OnClose(MyEntity __instance) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Patch\GridChange.cs:line 79
   at Patched_VRage.Game.Entity.MyEntityClose_0(Object )
   at MyServer_1._0.MySystems._0.GridHelper.ClearPirates() in C:\Users\SWQXDBA\RiderProjects\MyServer_1.0\Helpers\GridHelper.cs:line 122
   at MyServer_1._0.MySystems._0.PirateGener.FlushPirateRandom(MyServerPlugin plugin) in C:\Users\SWQXDBA\RiderProjects\MyServer_1.0\Pirates\PirateGener.cs:line 62
   at MyServer_1._0.MySystems._0.MyServerPlugin.UpDateSecondsBySetting(Action action, Int64 Seconds) in C:\Users\SWQXDBA\RiderProjects\MyServer_1.0\MyServerPlugin.cs:line 157
   at MyServer_1._0.MySystems._0.MyServerPlugin.Update() in C:\Users\SWQXDBA\RiderProjects\MyServer_1.0\MyServerPlugin.cs:line 594
   at Torch.Managers.PluginManager.UpdatePlugins() in C:\build\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 70
```
A strange error occurred in onclose() which prevented the grid from being deleted

**Comment by SWQXDBA** [comment]
Maybe it's a thread safety issue

**Comment by N1Ran** [comment]
Error is related to "TestPlugin".  Blocklimiter only showed up since it was triggered by the action of the said "Test Plugin".
