### ISSUE TITLE
Build v1.6.802

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#11]
08:34:21.4850 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 245
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at BlockLimiter.Utility.Grid.<>c__DisplayClass5_0.<UpdateLimit>b__0(MySlimBlock x) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at BlockLimiter.Utility.Grid.UpdateLimit(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157
   at BlockLimiter.BlockLimiter.MyCubeGridsOnBlockDestroyed(MyCubeGrid arg1, MySlimBlock arg2) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 93
   at System.DelegateExtensions.InvokeIfNotNull[T1,T2](Action`2 handler, T1 arg1, T2 arg2)
   at Sandbox.Game.Entities.MyCubeGrid.NotifyBlockRemoved(MySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveBlockInternal(MySlimBlock block, Boolean close, Boolean markDirtyDisconnects)
   at Sandbox.Game.Entities.MyCubeGrid.MoveBlocks(MyCubeGrid from, MyCubeGrid to, List`1 cubeBlocks, Int32 offset, Int32 count)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplitForGroup(MyCubeGrid originalGrid, List`1 splitBlocks, Group& group)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplits(MyCubeGrid originalGrid, List`1 splitBlocks, List`1 groups, MyTestDisconnectsReason reason, Boolean sync)
   at Sandbox.Game.Entities.Cube.MyDisconnectHelper.Disconnect(MyCubeGrid grid, MyTestDisconnectsReason reason, MySlimBlock testBlock, Boolean testDisconnect)
   at Sandbox.Game.Entities.MyCubeGrid.DetectDisconnects()
   at Sandbox.Game.Entities.MyCubeGrid.DoLazyUpdates()
   at Sandbox.Game.Entities.MyCubeGrid.UpdateBeforeSimulation()
   at Sandbox.Game.Entities.MyEntities.<>c.<UpdateBeforeSimulation>b__110_0(MyEntity x)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)

Suffix 1
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at BlockLimiter.Utility.Grid.UpdateLimit(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157
   at BlockLimiter.BlockLimiter.MyCubeGridsOnBlockDestroyed(MyCubeGrid arg1, MySlimBlock arg2) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 93
   at System.DelegateExtensions.InvokeIfNotNull[T1,T2](Action`2 handler, T1 arg1, T2 arg2)
   at Sandbox.Game.Entities.MyCubeGrid.NotifyBlockRemoved(MySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveBlockInternal(MySlimBlock block, Boolean close, Boolean markDirtyDisconnects)
   at Sandbox.Game.Entities.MyCubeGrid.MoveBlocks(MyCubeGrid from, MyCubeGrid to, List`1 cubeBlocks, Int32 offset, Int32 count)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplitForGroup(MyCubeGrid originalGrid, List`1 splitBlocks, Group& group)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplits(MyCubeGrid originalGrid, List`1 splitBlocks, List`1 groups, MyTestDisconnectsReason reason, Boolean sync)
   at Sandbox.Game.Entities.Cube.MyDisconnectHelper.Disconnect(MyCubeGrid grid, MyTestDisconnectsReason reason, MySlimBlock testBlock, Boolean testDisconnect)
   at Sandbox.Game.Entities.MyCubeGrid.DetectDisconnects()
   at Sandbox.Game.Entities.MyCubeGrid.DoLazyUpdates()
   at Sandbox.Game.Entities.MyCubeGrid.UpdateBeforeSimulation()
   at Sandbox.Game.Entities.MyEntities.<>c.<UpdateBeforeSimulation>b__110_0(MyEntity x)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)

Suffix 2
   at System.Threading.Monitor.Enter(Object obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemoveInternal(TKey key, TValue& value, Boolean matchValue, TValue oldValue)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)
   at BlockLimiter.Utility.Grid.UpdateLimit(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 153
   at Sandbox.MySandboxGame.ProcessInvoke()

08:34:22.0007 [FATAL]  Initializer: System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 255
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 255
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
08:34:22.0007 [INFO]   Initializer: Generating minidump at c:\SERVER2\Instance\Minidump.dmp
08:34:22.0007 [ERROR]  Initializer: Keen broke the minidump, sorry.
08:34:27.3599 [INFO]   SteamCMD: Checking for DS updates.
08:34:32.9067 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
=========================================
08:47:18.2026 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at BlockLimiter.Utility.Grid.UpdateLimit(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 245
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at BlockLimiter.Utility.Grid.<>c__DisplayClass5_0.<UpdateLimit>b__0(MySlimBlock x) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157

Suffix 1
   at BlockLimiter.Utility.Grid.<>c__DisplayClass5_0.<UpdateLimit>b__0(MySlimBlock x) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157

Suffix 2
   at BlockLimiter.Utility.Grid.<>c__DisplayClass5_0.<UpdateLimit>b__0(MySlimBlock x) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157

08:47:18.4682 [FATAL]  Initializer: System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 255
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 255
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
08:47:18.4682 [INFO]   Initializer: Generating minidump at c:\SERVER2\Instance\Minidump.dmp
08:47:18.4682 [ERROR]  Initializer: Keen broke the minidump, sorry.
08:47:23.8431 [INFO]   SteamCMD: Checking for DS updates.
08:47:29.6398 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
======================================

When undocking 1 grid from other grid, torch freeze and stuck.

**Comment by dorimanx** [comment]
09:12:14.0161 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at BlockLimiter.BlockLimiter.MyCubeGridsOnBlockDestroyed(MyCubeGrid arg1, MySlimBlock arg2) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 93
   at System.DelegateExtensions.InvokeIfNotNull[T1,T2](Action`2 handler, T1 arg1, T2 arg2)
   at Sandbox.Game.Entities.MyCubeGrid.NotifyBlockRemoved(MySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveBlockInternal(MySlimBlock block, Boolean close, Boolean markDirtyDisconnects)
   at Sandbox.Game.Entities.MyCubeGrid.MoveBlocks(MyCubeGrid from, MyCubeGrid to, List`1 cubeBlocks, Int32 offset, Int32 count)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplitForGroup(MyCubeGrid originalGrid, List`1 splitBlocks, Group& group)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplits(MyCubeGrid originalGrid, List`1 splitBlocks, List`1 groups, MyTestDisconnectsReason reason, Boolean sync)
   at Sandbox.Game.Entities.Cube.MyDisconnectHelper.Disconnect(MyCubeGrid grid, MyTestDisconnectsReason reason, MySlimBlock testBlock, Boolean testDisconnect)
   at Sandbox.Game.Entities.MyCubeGrid.DetectDisconnects()
   at Sandbox.Game.Entities.MyCubeGrid.DoLazyUpdates()
   at Sandbox.Game.Entities.MyCubeGrid.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.<>c.<UpdateAfterSimulation>b__113_0(MyEntity x)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 245
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at BlockLimiter.Utility.Grid.<>c__DisplayClass5_0.<UpdateLimit>b__0(MySlimBlock x) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at BlockLimiter.Utility.Grid.UpdateLimit(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157

Suffix 1
   at System.Threading.Monitor.Enter(Object obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(TKey key, TValue value, Boolean updateIfExists, Boolean acquireLock, TValue& resultingValue)
   at System.Collections.Concurrent.ConcurrentDictionary`2.set_Item(TKey key, TValue value)
   at BlockLimiter.Utility.Grid.UpdateLimit(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 149

Suffix 2
   at BlockLimiter.Utility.Block.IsMatch(MyCubeBlockDefinition block, LimitItem item) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 242
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at BlockLimiter.Utility.Grid.UpdateLimit(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Grid.cs:line 157


09:12:14.2369 [FATAL]  Initializer: System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 255
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 255
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
09:12:14.2369 [INFO]   Initializer: Generating minidump at c:\SERVER2\Instance\Minidump.dmp

**Comment by N1Ran** [comment]
pushing out a fix for this now.  Let me know if you still get this error
