### ISSUE TITLE
Torch freeze, but has chance to recover.. please check.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#16]
16:28:35.7322 [ERROR]  Torch: Server watchdog detected that the server was frozen for at least 60 seconds.
16:28:50.7492 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at BlockLimiter.BlockLimiter.<>c.<ResetLimits>b__31_4() in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 304
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_hacks\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_hacks\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at System.Threading.Monitor.Enter(Object obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(TKey key, TValue value, Boolean updateIfExists, Boolean acquireLock, TValue& resultingValue)
   at System.Collections.Concurrent.ConcurrentDictionary`2.set_Item(TKey key, TValue value)
   at BlockLimiter.Utility.Block.UpdatePlayerLimits(Int64 id) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 353

Suffix 1
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 90
   at BlockLimiter.Utility.Block.UpdatePlayerLimits(Int64 id) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 346

Suffix 2
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 90
   at BlockLimiter.Utility.Block.UpdatePlayerLimits(Int64 id) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 346

**Comment by N1Ran** [comment]
Blocklimiter is not the cause.  That just shows which threads got affected by the freeze and since the limiter needs the server to be running, it would show up on the stack trace.  You need to find the real cause for the freeze.

**Comment by dorimanx** [comment]
well no freeze without block limiter, so it's started right after we added it to server, also when server boot, it's takes 8min to boot, without plugin 3min.
Any change in plugin menu will freeze torch for 3min..
We really like to use it, it's great plugin, can you somehow skip counting all blocks at start?,
or stretch somehow not blocking the main start process.

Thank you for your work.

**Comment by dorimanx** [comment]
It's possible that start "hang" for us is from other plugin that conflict with block limiter, i will check and update you.
Thank you.

**Comment by N1Ran** [comment]
The initial freeze is normal.  Don't do anything till it's done.  It calculates all current blocks and ownership on statup

**Comment by N1Ran** [comment]
Going to disable auto update on changes.  This should allow making changes while server is running, but the updates won't take effect till next restart or when limits are manually updated
