### ISSUE TITLE
Crash on blocklimiter update.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#43]
`
19:16:59.6060 [FATAL]  Initializer: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 105
   at BlockLimiter.Utility.UpdateLimits.PlayerLimit(Int64 id) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 25
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 100
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeSuccess(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId, Int64 senderId)
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeRequest(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6](T1 arg1, T6 arg6, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SendFactionChange(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at Sandbox.Game.Multiplayer.MyFactionCollection.VRage.Game.ModAPI.IMyFactionCollection.DemoteMember(Int64 factionId, Int64 playerId)
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdate(Tuple`2 tmp, Boolean usetime)
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdatesLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 105
   at BlockLimiter.Utility.UpdateLimits.PlayerLimit(Int64 id) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 25
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 100
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeSuccess(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId, Int64 senderId)
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeRequest(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6](T1 arg1, T6 arg6, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SendFactionChange(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at Sandbox.Game.Multiplayer.MyFactionCollection.VRage.Game.ModAPI.IMyFactionCollection.DemoteMember(Int64 factionId, Int64 playerId)
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdate(Tuple`2 tmp, Boolean usetime)
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdatesLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

`

**Comment by dorimanx** [comment]
something about faction update that called by serverjump plugin.
all clients got crash too... not just server.

**Comment by N1Ran** [comment]
I have a fix for the server crash, but do you have any client log?

**Comment by dorimanx** [comment]
sadly no, but it's also was about faction change event.. client lor is rewritten each game start..
next time i will save it if there is some info about blocklimiter.

**Comment by N1Ran** [comment]
This shouldn't crash server again.  Get me logs to clients if they are still having issues
