### ISSUE TITLE
[1.6.4] Disconnect when loading BP into projector

### ISSUE THREAD

**Issue by scytero** [N1Ran/BlockLimiter#5]
Hi there,

my players told me about a problem, that seems to be related to the last update:
As long, as any of the limiting rules includes the *Restrict Projection* option, they immediately get disconnected whenever they try to load a BP into the projector block. 

While I had no time to confirm this behaviour, removign all Proj. restriction fixed the problem for now. 

Further, I could find this logged errors, that may be related toi the problem (as the only came up now and was followed by the disconnect of the user(s) trying):
```log
16:35:31.6528 [ERROR]  Keen: System.NullReferenceException: Object reference not set to an instance of an object.
   at BlockLimiter.Utility.Block.<>c__DisplayClass3_0.<IsMatch>b__0(String x) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 262
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at BlockLimiter.Utility.Block.IsMatch(MyCubeBlockDefinition block, LimitItem item) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 261
   at BlockLimiter.Utility.Block.ProjectBlock(MyObjectBuilder_CubeBlock block, Int64 playerId, MyObjectBuilder_CubeGrid grid) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 372
   at BlockLimiter.Patch.ProjectionPatch.PrefixNewBlueprint(MyProjectorBase __instance, List`1& projectedGrids) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Patch\ProjectionPatch.cs:line 83
   at Patched_Sandbox.Game.Entities.Blocks.MyProjectorBaseOnNewBlueprintSuccess_0(Object , List`1 )
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlockLimiter.Utility.Block.<>c__DisplayClass3_0.<IsMatch>b__0(String x) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 262
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at BlockLimiter.Utility.Block.IsMatch(MyCubeBlockDefinition block, LimitItem item) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 261
   at BlockLimiter.Utility.Block.ProjectBlock(MyObjectBuilder_CubeBlock block, Int64 playerId, MyObjectBuilder_CubeGrid grid) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 372
   at BlockLimiter.Patch.ProjectionPatch.PrefixNewBlueprint(MyProjectorBase __instance, List`1& projectedGrids) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Patch\ProjectionPatch.cs:line 83
   at Patched_Sandbox.Game.Entities.Blocks.MyProjectorBaseOnNewBlueprintSuccess_0(Object , List`1 )
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
16:35:31.6549 [INFO]   Torch.Managers.MultiplayerManagerBase: <name> (<steam64-id>) Disconnected.
```

Until the update, I did not experience this problem, nor did a player tell me about.

**Comment by N1Ran** [comment]
Need link to bp. Could be an issue with the bp specifically

**Comment by scytero** [comment]
No spefic blueprint. They tried with different ones, both local and workshop, different sizes (100 - 4000 blocks) and PCU

**Comment by N1Ran** [comment]
ok, give my your config then.  Will see if I can recreate

**Comment by scytero** [comment]
[PBLimiter.cfg.txt](https://github.com/N1Ran/BlockLimiter/files/4243040/PBLimiter.cfg.txt)
(renamed, as uploads of .cfg are not supported - just remove the .txt postfix)

**Comment by scytero** [comment]
[BlockLimiter.cfg.txt](https://github.com/N1Ran/BlockLimiter/files/4243043/BlockLimiter.cfg.txt)

(renamed, as uploads of .cfg are not supported - just remove the .txt postfix)

The rules for Pistons and Rotors were the ones, that had the blueprint option activated.

**Comment by N1Ran** [comment]
fixed
