### ISSUE TITLE
Found new warning from plugin.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#50]
Hi,
Sometimes i see this warning from plugin, random, at our servers.

`
19:43:46.8902 [WARN]   Handler Problems: 3300000 - System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 108
   at BlockLimiter.Punishment.Punish.Handle() in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Punishment\Punish.cs:line 44
   at BlockLimiter.BlockLimiter.<>c__DisplayClass19_0.<PluginProcessing>b__0() in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 197

`

**Comment by N1Ran** [comment]
It's just letting you know block count changed as it was running the punish method.  It's nothing to be concerned about but will look into making it happen less
