### ISSUE TITLE
i see this in log, and server just crashed.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#53]
`

2020/06/16 14:44:37.078 [ERROR]  Keen: System.NullReferenceException: Object reference not set to an instance of an object.
   at BlockLimiter.Utility.Utilities.IsExcepted(Int64 obj, List`1 exceptions) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Utilities.cs:line 162
   at BlockLimiter.Utility.Block.IsWithinLimits(MyCubeBlockDefinition def, Int64 ownerId, Int64 gridId, Int32 count) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 124
   at BlockLimiter.Patch.BuildBlockPatch.BuildBlocksRequest(MyCubeGrid __instance, HashSet`1 locations) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Patch\BuildBlockPatch.cs:line 119
   at Patched_Sandbox.Game.Entities.MyCubeGridBuildBlocksRequest_0(Object locations, MyBlockVisuals builderEntityId, HashSet`1 instantBuild, Int64 ownerId, Boolean , Int64 )
   at Sandbox.Game.Entities.MyCubeGrid.BuildBlocksRequest<>Sandbox_Game_Entities_MyCubeGrid<>MyBlockVisuals#System_Collections_Generic_HashSet`1<Sandbox_Game_Entities_MyCubeGrid<>MyBlockLocation>#System_Int64#System_Boolean#System_Int64.Invoke(MyCubeGrid& this, MyBlockVisuals& visuals, HashSet`1& locations, Int64& builderEntityId, Boolean& instantBuild, Int64& ownerId, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)

`
I have enabled the shutoff unowned blocks.
all the rest is as was, i have never seen this error before, but i see that plugin was updated.

**Comment by dorimanx** [comment]
i am rolling back to previous version our servers are crashing! people cannot place blocks. and this error is reported all the time.

**Comment by dorimanx** [comment]
Rolled back, and all seems to be stable again.

**Comment by reeths** [comment]
having same issue here
12:32:10.5427 [ERROR]  Keen: System.NullReferenceException: Object reference not set to an instance of an object.
   at BlockLimiter.Utility.Utilities.IsExcepted(Int64 obj, List`1 exceptions) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Utilities.cs:line 162
   at BlockLimiter.Utility.Block.IsWithinLimits(MyCubeBlockDefinition def, Int64 ownerId, Int64 gridId, Int32 count) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 124
   at BlockLimiter.Patch.BuildBlockPatch.BuildBlocksRequest(MyCubeGrid __instance, HashSet`1 locations) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Patch\BuildBlockPatch.cs:line 119
   at Patched_Sandbox.Game.Entities.MyCubeGridBuildBlocksRequest_0(Object locations, MyBlockVisuals builderEntityId, HashSet`1 instantBuild, Int64 ownerId, Boolean , Int64 )
   at Sandbox.Game.Entities.MyCubeGrid.BuildBlocksRequest<>Sandbox_Game_Entities_MyCubeGrid<>MyBlockVisuals#System_Collections_Generic_HashSet`1<Sandbox_Game_Entities_MyCubeGrid<>MyBlockLocation>#System_Int64#System_Boolean#System_Int64.Invoke(MyCubeGrid& this, MyBlockVisuals& visuals, HashSet`1& locations, Int64& builderEntityId, Boolean& instantBuild, Int64& ownerId, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlockLimiter.Utility.Utilities.IsExcepted(Int64 obj, List`1 exceptions) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Utilities.cs:line 162
   at BlockLimiter.Utility.Block.IsWithinLimits(MyCubeBlockDefinition def, Int64 ownerId, Int64 gridId, Int32 count) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\Block.cs:line 124
   at BlockLimiter.Patch.BuildBlockPatch.BuildBlocksRequest(MyCubeGrid __instance, HashSet`1 locations) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Patch\BuildBlockPatch.cs:line 119
   at Patched_Sandbox.Game.Entities.MyCubeGridBuildBlocksRequest_0(Object locations, MyBlockVisuals builderEntityId, HashSet`1 instantBuild, Int64 ownerId, Boolean , Int64 )
   at Sandbox.Game.Entities.MyCubeGrid.BuildBlocksRequest<>Sandbox_Game_Entities_MyCubeGrid<>MyBlockVisuals#System_Collections_Generic_HashSet`1<Sandbox_Game_Entities_MyCubeGrid<>MyBlockLocation>#System_Int64#System_Boolean#System_Int64.Invoke(MyCubeGrid& this, MyBlockVisuals& visuals, HashSet`1& locations, Int64& builderEntityId, Boolean& instantBuild, Int64& ownerId, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)

**Comment by N1Ran** [comment]
I need a cfg file to test this out and also what players tried to do before crash

**Comment by N1Ran** [comment]
fixed
