### ISSUE TITLE
Server Crash with LOG.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#56]
`

2020/06/29 22:06:22.314 [FATAL]  Initializer: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 108
   at BlockLimiter.Utility.UpdateLimits.PlayerLimit(Int64 id) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 25
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in C:\Users\Olatide\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 104
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeSuccess(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId, Int64 senderId)
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeRequest(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6](T1 arg1, T6 arg6, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SendFactionChange(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at Sandbox.Game.Multiplayer.MyFactionCollection.VRage.Game.ModAPI.IMyFactionCollection.PromoteMember(Int64 factionId, Int64 playerId)
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdate(Tuple`2 tmp, Boolean usetime)
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdatesLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

`

**Comment by N1Ran** [comment]
did this happen because a player changed faction?

**Comment by dorimanx** [comment]
it's is possible, as i also see crash from ServerJump sync, what i cant understand is what went wrong,
After this crash i have issued full sync with DB from all servers to sync factions and players,
And so far no such errors.

Just want to show you that some possible crash can happen with faction changes.

**Comment by dorimanx** [comment]
No more issues detected, so no point to hold this open.
