### ISSUE TITLE
Server crash when there's a faction sync issue with Foogs ServerJump

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#59]
I highly suspect this isn't entirely on the head of Blocklimiter, but it is a crash we only get with blocklimiter. Happens after  a failed faction sync event with Foogs Server jump screws up a player and what faction they are in (so that's the real trigger here).

Is there anything you're able / willing to do to prevent blocklimiter from crashing the server on one of these failed sync events in foogs serverjump?

```
13:09:26.9752 [WARN]   SigmaJump: FactUpd: Faction update get: SIS - 76561198337008073 use time = True
13:09:26.9752 [WARN]   SigmaJump: FactUpd: Player not exist on server, trying to create..
13:09:26.9752 [WARN]   SigmaJump: got here
13:09:26.9752 [WARN]   SigmaJump: got here wot
13:09:26.9752 [WARN]   SigmaJump: fsdfs
13:09:26.9752 [WARN]   SigmaJump: got here tooo
13:09:26.9752 [WARN]   SigmaJump: Create Remote Player from DB Localy - done! identityID = 151899506377009819
13:09:27.0065 [WARN]   SigmaJump: FactUpd: FoundbyID : False | Found by tag: False
13:09:27.0065 [WARN]   SigmaJump: FactUpd: Faction not found or wrong owner
13:09:27.0377 [WARN]   SigmaJump: RaiseStaticEvent sended!~!!!!!!!!!!!!!!!!
13:09:27.5065 [FATAL]  Initializer: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 108
   at BlockLimiter.Utility.UpdateLimits.FactionLimit(Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 112
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 101
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStateInternal(Int64 factionId, IMyFaction defaultFaction, MyFactionDefinition defaultFactionDef)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStates(Int64 recivedFactionId)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ServerJumpNS.Util.CreateRemoteFactionServer(Int64 factionid, Int64 founderId, String factionTag, String factionName, String description, String privateInfo, MyFactionDefinition factionDef) in C:\space\sigma-jump-plugin\Utilities.cs:line 1326
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdate(Tuple`2 tmp, Boolean usetime) in C:\space\sigma-jump-plugin\FactionAndPlyersSync\MySQLConnect.cs:line 483
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdatesLoop() in C:\space\sigma-jump-plugin\FactionAndPlyersSync\MySQLConnect.cs:line 1866
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 108
   at BlockLimiter.Utility.UpdateLimits.FactionLimit(Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 112
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 101
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStateInternal(Int64 factionId, IMyFaction defaultFaction, MyFactionDefinition defaultFactionDef)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStates(Int64 recivedFactionId)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ServerJumpNS.Util.CreateRemoteFactionServer(Int64 factionid, Int64 founderId, String factionTag, String factionName, String description, String privateInfo, MyFactionDefinition factionDef) in C:\space\sigma-jump-plugin\Utilities.cs:line 1326
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdate(Tuple`2 tmp, Boolean usetime) in C:\space\sigma-jump-plugin\FactionAndPlyersSync\MySQLConnect.cs:line 483
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.FactionUpdatesLoop() in C:\space\sigma-jump-plugin\FactionAndPlyersSync\MySQLConnect.cs:line 1866
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
13:09:27.5065 [FATAL]  Initializer: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 108
   at BlockLimiter.Utility.UpdateLimits.FactionLimit(Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 112
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 101
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStateInternal(Int64 factionId, IMyFaction defaultFaction, MyFactionDefinition defaultFactionDef)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStates(Int64 recivedFactionId)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetBlocks(HashSet`1 entities) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 108
   at BlockLimiter.Utility.UpdateLimits.FactionLimit(Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 112
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 101
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStateInternal(Int64 factionId, IMyFaction defaultFaction, MyFactionDefinition defaultFactionDef)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SetDefaultFactionStates(Int64 recivedFactionId)
13:09:27.5065 [INFO]   Initializer: Generating minidump at C:\Torch-Servers\SEDS8\Instance\Minidump.dmp
```

**Comment by kontu** [comment]
[BlockLimiter.txt](https://github.com/N1Ran/BlockLimiter/files/4909442/BlockLimiter.txt)
Blocklimiter config attached for reference

**Comment by dorimanx** [comment]
We had same issue. but it's rare... no idea where it's has to be fixed, in both plugins! or just one of them.

**Comment by N1Ran** [comment]
looks like the faction info was not properly synced.  I'll ask foogs what he does to change that and have limiter just wait before updating whenever serverjump involved.  For now, I'd suggest going over your faction info and making sure they are properly synced among connected servers

**Comment by kontu** [comment]
Yea - just sucks because as soon as a player changes the founder of their faction, it breaks the sync like that every time so we'd see the crash with blocklimiter each time. Not really easy to keep on top of with >300 factions in the database

**Comment by N1Ran** [comment]
I'll try to duplicate the founder change crash from BL and see if it can be fixed from just that

**Comment by BobDaRoss** [comment]
22:08:59.8108 [INFO]   ServerNetwork.Sync.ChatSync: PlayerPos: X:-427096.777261757 Y:-1021127.74551496 Z:2857954.09155253
22:08:59.8108 [WARN]   ServerNetwork.Sync.ChatSync: Returning false!
22:09:02.2633 [INFO]   ServerNetwork.Sync.FactionSync: Discovered New Faction: 235350171975365002
22:09:02.2633 [INFO]   ServerNetwork.Sync.FactionSync: Discovered New Faction: 258961289160008772
22:09:02.2790 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at BlockLimiter.Utility.GridCache.<>c__DisplayClass15_0.<GetFactionBlocks>b__1(MySlimBlock x) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 128
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetFactionBlocks(HashSet`1 entities, Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 0
   at BlockLimiter.Utility.UpdateLimits.FactionLimit(Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 100
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 111
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Patched_Sandbox.Game.Multiplayer.MyFactionCollectionFactionStateChangeSuccess_0(MyFactionStateChange fromFactionId, Int64 toFactionId, Int64 playerId, Int64 senderId, Int64 )
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeRequest(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6](T1 arg1, T6 arg6, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SendFactionChange(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at Sandbox.Game.AI.MyAgentBot.Init(MyObjectBuilder_Bot botBuilder)
   at Sandbox.Game.AI.MyBotFactoryBase.CreateBot(MyPlayer player, MyObjectBuilder_Bot botBuilder, MyBotDefinition botDefinition)
   at Sandbox.Game.AI.MyAIComponent.CreateBot(Int32 playerNumber, MyObjectBuilder_Bot botBuilder)
   at Sandbox.Game.AI.MyAIComponent.PlayerCreated(PlayerId playerId)
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.OnNewPlayerSuccess(UInt64 clientSteamId, Int32 playerSerialId)
   at Patched_Sandbox.Game.Multiplayer.MyPlayerCollectionOnNewPlayerRequest_0(UInt64 playerSerialId, Int32 displayName, String characterModel, String realPlayer, Boolean initialPlayer, Boolean )
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6,T7,T8](T1 arg1, T8 arg8, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.RequestNewPlayer(Int32 serialNumber, String playerName, String characterModel, Boolean realPlayer, Boolean initialPlayer)
   at Sandbox.Game.AI.MyAIComponent.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlockLimiter.Utility.GridCache.<>c__DisplayClass15_0.<GetFactionBlocks>b__1(MySlimBlock x) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 128
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at BlockLimiter.Utility.GridCache.GetFactionBlocks(HashSet`1 entities, Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 0
   at BlockLimiter.Utility.UpdateLimits.FactionLimit(Int64 id) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\Utility\UpdateLimits.cs:line 100
   at BlockLimiter.BlockLimiter.FactionsOnFactionStateChanged(MyFactionStateChange factionState, Int64 fromFaction, Int64 toFaction, Int64 playerId, Int64 senderId) in C:\Users\Olatide\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 111
   at System.Action`5.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Patched_Sandbox.Game.Multiplayer.MyFactionCollectionFactionStateChangeSuccess_0(MyFactionStateChange fromFactionId, Int64 toFactionId, Int64 playerId, Int64 senderId, Int64 )
   at Sandbox.Game.Multiplayer.MyFactionCollection.FactionStateChangeRequest(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6](T1 arg1, T6 arg6, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyFactionCollection.SendFactionChange(MyFactionStateChange action, Int64 fromFactionId, Int64 toFactionId, Int64 playerId)
   at Sandbox.Game.AI.MyAgentBot.Init(MyObjectBuilder_Bot botBuilder)
   at Sandbox.Game.AI.MyBotFactoryBase.CreateBot(MyPlayer player, MyObjectBuilder_Bot botBuilder, MyBotDefinition botDefinition)
   at Sandbox.Game.AI.MyAIComponent.CreateBot(Int32 playerNumber, MyObjectBuilder_Bot botBuilder)
   at Sandbox.Game.AI.MyAIComponent.PlayerCreated(PlayerId playerId)
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.OnNewPlayerSuccess(UInt64 clientSteamId, Int32 playerSerialId)
   at Patched_Sandbox.Game.Multiplayer.MyPlayerCollectionOnNewPlayerRequest_0(UInt64 playerSerialId, Int32 displayName, String characterModel, String realPlayer, Boolean initialPlayer, Boolean )
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6,T7,T8](T1 arg1, T8 arg8, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.RequestNewPlayer(Int32 serialNumber, String playerName, String characterModel, Boolean realPlayer, Boolean initialPlayer)
   at Sandbox.Game.AI.MyAIComponent.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Getting the same error with my Sectoring plugin & Datasync

**Comment by N1Ran** [comment]
issue should be addressed in latest version
