### ISSUE TITLE
[BUG] Method not found

### ISSUE THREAD

**Issue by twistedgrim** [N1Ran/BlockLimiter#84]
Updated to the new 198 torch version and hit a bug

12:30:24.5298 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Int64 Sandbox.Game.World.MyFaction.get_FactionId()'.
   at BlockLimiter.Utility.Block.IncreaseCount(MyCubeBlockDefinition def, Int64 playerId, Int32 amount, Int64 gridId)
   at BlockLimiter.BlockLimiter.MyEntitiesOnOnEntityAdd(MyEntity entity) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 96
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Entities.MyEntities.RaiseEntityAdd(MyEntity entity)
   at Sandbox.Game.Entities.MyEntities.Add(MyEntity entity, Boolean insertIntoScene)
   at Sandbox.Game.Entities.MyEntities.CreateFromObjectBuilderAndAdd(MyObjectBuilder_EntityBase objectBuilder, Boolean fadeIn)
   at MeridiusIX.PTA_SessionCore.UpdateBeforeSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\Users\Administrator\Desktop\Personal Projects\torch\Torch\VRageGame.cs:line 296
   at Torch.VRageGame.Run() in C:\Users\Administrator\Desktop\Personal Projects\torch\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Int64 Sandbox.Game.World.MyFaction.get_FactionId()'.
   at BlockLimiter.Utility.Block.IncreaseCount(MyCubeBlockDefinition def, Int64 playerId, Int32 amount, Int64 gridId)
   at BlockLimiter.BlockLimiter.MyEntitiesOnOnEntityAdd(MyEntity entity) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\BlockLimiter.cs:line 96
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Entities.MyEntities.RaiseEntityAdd(MyEntity entity)
   at Sandbox.Game.Entities.MyEntities.Add(MyEntity entity, Boolean insertIntoScene)
   at Sandbox.Game.Entities.MyEntities.CreateFromObjectBuilderAndAdd(MyObjectBuilder_EntityBase objectBuilder, Boolean fadeIn)
   at MeridiusIX.PTA_SessionCore.UpdateBeforeSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\Users\Administrator\Desktop\Personal Projects\torch\Torch\VRageGame.cs:line 296
   at Torch.VRageGame.Run() in C:\Users\Administrator\Desktop\Personal Projects\torch\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by N1Ran** [comment]
fixed.  update your plugin
