### ISSUE TITLE
Invalid characters in path

### ISSUE THREAD

**Issue by EasterncheesE** [N1Ran/BlockLimiter#85]
18:44:46.8663 [ERROR]  BlockLimiter.Settings.BlockLimiterConfig: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at BlockLimiter.Settings.BlockLimiterConfig.Load() in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Settings\BlockLimiterConfig.cs:line 391
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at BlockLimiter.Settings.BlockLimiterConfig.Load() in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Settings\BlockLimiterConfig.cs:line 391
18:44:46.8663 [WARN]   Concealment: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Concealment.ConcealmentPlugin.Init(ITorchBase torch) in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealmentPlugin.cs:line 63
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Concealment.ConcealmentPlugin.Init(ITorchBase torch) in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealmentPlugin.cs:line 63
18:44:46.8663 [FATAL]  Initializer: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Concealment.ConcealmentPlugin.Init(ITorchBase torch) in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealmentPlugin.cs:line 72
   at Torch.Managers.PluginManager.LoadPlugins() in C:\build\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 202
   at Torch.TorchBase.Init() in C:\build\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 339
   at Torch.Server.TorchServer.Init() in C:\build\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 143
   at Torch.Server.Initializer.Run() in C:\build\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 135
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\build\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Concealment.ConcealmentPlugin.Init(ITorchBase torch) in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealmentPlugin.cs:line 72
   at Torch.Managers.PluginManager.LoadPlugins() in C:\build\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 202
   at Torch.TorchBase.Init() in C:\build\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 339
   at Torch.Server.TorchServer.Init() in C:\build\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 143
   at Torch.Server.Initializer.Run() in C:\build\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 135
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\build\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75

Getting this on blocklimiter 1.7.107

Please advise me how to fix it. It's dedicated server, GTXgaming hosting, so, basically, i don't even have acces to both c:\ and d:\

**Comment by EasterncheesE** [comment]
Basically, server runs fine and everything works, but there are sudden crashes every few hourse. Then it restarts and keeps working quite well.

**Comment by N1Ran** [comment]
That usually means there's issue with the path to the config or log file. Just report to GTX and make sure your path is correct
