### ISSUE TITLE
It broke with the update.

### ISSUE THREAD

**Issue by marksman1907** [N1Ran/BlockLimiter#98]
With the 26.09.2021 update, it started to cause the server not to work.

13:58:05.0625 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at VRage.FastResourceLock.AcquireExclusive()
   at BlockLimiter.Utility.GridCache.RemoveBlocks(HashSet`1 blocks) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 67
   at BlockLimiter.Utility.GridCache.RemoveGrid(MyCubeGrid grid) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Utility\GridCache.cs:line 51
   at BlockLimiter.Patch.GridChange.OnClose(MyEntity __instance) in D:\Sync\ProgramFiles\VisualStudio\source\repos\BlockLimiter\BlockLimiter\Patch\GridChange.cs:line 83
   at Patched_VRage.Game.Entity.MyEntityClose_0(Object )
   at Sandbox.Game.Entities.Cube.MyGridClipboard.ChangeClipboardPreview(Boolean visible, List`1 previewGrids, List`1 copiedGrids)
   at Sandbox.Game.Entities.Cube.MyGridClipboard.Deactivate(Boolean afterPaste)
   at Sandbox.Game.Entities.Blocks.MyProjectorBase.RemoveProjection(Boolean keepProjection)
   at Sandbox.Game.Entities.Blocks.MyProjectorBase.OnEnabledChanged(MyTerminalBlock myTerminalBlock)
   at System.Action`1.Invoke(T obj)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at Patched_Sandbox.Game.Entities.Cube.MyFunctionalBlockOnEnabledChanged_0(Object )
   at System.Action`1.Invoke(T obj)
   at VRage.Sync.SyncBase.RaiseValueChanged(Boolean notify)
   at VRage.Sync.Sync`2.SetValue(T& newValue, Boolean validate, Boolean ignoreSyncDirection, Boolean received)
   at Concealment.ConcealGroup.DisableProjectors(MyCubeGrid grid) in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealGroup.cs:line 142
   at Concealment.ConcealGroup.Conceal() in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealGroup.cs:line 165
   at Concealment.ConcealmentPlugin.ConcealGroup(ConcealGroup group) in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealmentPlugin.cs:line 218
   at Concealment.ConcealmentPlugin.ConcealGrids(Double distanceFromPlayers) in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealmentPlugin.cs:line 330
   at Concealment.ConcealmentPlugin.Update() in C:\build\workspace\Torch_Concealment_master\Concealment\ConcealmentPlugin.cs:line 99
   at Torch.Managers.PluginManager.UpdatePlugins() in C:\build\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 70
   at Torch.Server.TorchServer.Update() in C:\build\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 254
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 316
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)

Suffix 1
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)

Suffix 2
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)

13:58:05.0625 [FATAL]  Initializer: System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\build\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 289
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\build\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 289
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by lumbyjack** [comment]
public static void RemoveBlocks(HashSet<MySlimBlock> blocks)
        {
            using (_entityLock.AcquireExclusiveUsing())
            {
                foreach (var block in blocks)
                {
                    _blockCache.Remove(block);
                }
            }
        }
        
        this function does the kill on torch

**Comment by N1Ran** [comment]
.404 should fix this but can't be tested since I have no sample to test it.  The issue is can not be reproduced on my end.

**Comment by marksman1907** [comment]
It looks fixed. It is active on my server now.
